// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTgjdYwB7T3U8ejJP2_4U9xt1siiCuIGQ',
    appId: '1:6454599497:web:6dec57bccf89a76c150498',
    messagingSenderId: '6454599497',
    projectId: 'lightstep-50379',
    authDomain: 'lightstep-50379.firebaseapp.com',
    storageBucket: 'lightstep-50379.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_ph-TtnSanMknt0uvfjjt57q3jH3SV04',
    appId: '1:6454599497:android:e03f7aaf2031138e150498',
    messagingSenderId: '6454599497',
    projectId: 'lightstep-50379',
    storageBucket: 'lightstep-50379.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWggdOfs2DB21tDqU7E6EhMLIQTGAXBDk',
    appId: '1:6454599497:ios:89468cf681449dbb150498',
    messagingSenderId: '6454599497',
    projectId: 'lightstep-50379',
    storageBucket: 'lightstep-50379.firebasestorage.app',
    iosBundleId: 'com.example.lightstepdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWggdOfs2DB21tDqU7E6EhMLIQTGAXBDk',
    appId: '1:6454599497:ios:89468cf681449dbb150498',
    messagingSenderId: '6454599497',
    projectId: 'lightstep-50379',
    storageBucket: 'lightstep-50379.firebasestorage.app',
    iosBundleId: 'com.example.lightstepdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTgjdYwB7T3U8ejJP2_4U9xt1siiCuIGQ',
    appId: '1:6454599497:web:49ea42767697e706150498',
    messagingSenderId: '6454599497',
    projectId: 'lightstep-50379',
    authDomain: 'lightstep-50379.firebaseapp.com',
    storageBucket: 'lightstep-50379.firebasestorage.app',
  );

}